{{- $app := printf "%s-postgres" .Values.resource.name -}}
{{- $spec := dict }}
{{- $_ := merge $spec .Values.resource.spec .Values.default -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.resource.name }}-postgres
  labels:
    app: {{ .Values.resource.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  SOA_USERNAME: {{ default .Values.resource.name .Values.resource.spec.username | b64enc | quote }}{{- if .Values.resource.spec.password }}
  POSTGRES_PASSWORD: {{ .Values.resource.spec.password | b64enc | quote }}
  SOA_PASSWORD: {{ .Values.resource.spec.password | b64enc | quote }}{{- end }}
  SOA_DATABASE: {{ default .Values.resource.name .Values.resource.spec.database | b64enc | quote }}